home/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.views.static import serve
from mainpage import views as mainpage_views

urlpatterns = [
    path('', mainpage_views.index),
    path('admin/', admin.site.urls),
    path('mainpage/', include('mainpage.urls')),
    path('stockans/', include('stockans.urls')),
]

if settings.DEBUG:
    urlpatterns += [
        re_path(r'^static/(?P<path>.*)$', serve, {
            'document_root': settings.STATIC_ROOT,
        }),
        re_path(r'^media/(?P<path>.*)$', serve, {
            'document_root': settings.MEDIA_ROOT,
        }),
    ]

stockans/urls.py
from django.urls import path
from . import views as stockans_views

# mainpage urlpatterns
app_name = 'stockans'
urlpatterns = [
    path('profile_list/', stockans_views.profile_list, name='profile_list'),
    path('update_stockprofile/', stockans_views.update_stockprofile, name='update_stockprofile'),
    path('price_online/', stockans_views.price_online, name='price_online'),
    path('update_price_online_data/', stockans_views.update_price_online_data, name='update_price_online_data'),
]

stockans/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _
from django.core.exceptions import ObjectDoesNotExist
from django.core.exceptions import ValidationError


class ExtraStockProfileManager(models.Manager):
    def update_by_bulk(self, list):
        """
        捆绑更新记录
        :return:
        """
        if list is not None:
            for instance in list:
                self.update_or_create(
                    stock_code=instance[4],
                    defaults={
                    'company_code': instance[0],
                    'company_abb': instance[1],
                    'exchange_no': instance[2],
                    'stock_style': instance[3],
                    'stock_abb': instance[5],
                    'listing_date': instance[6],
                    'general_capital': instance[7],
                    'circulating_capital': instance[8],
                    'by_sector': instance[9],
                }
                )
            return len(list)
        else:
            return 0


class ExtraAttentionedStockManager(models.Manager):
    def get_attentioned_stock_by_user(self, request):
        """
        通过登录的用户获取关注的股票
        :param request:
        :return:
        """
        stock_queryset = self.filter(user=request.user).values('stock__stock_code', 'stock__stock_abb')
        return stock_queryset


class ExtraStockPriceOnLineManager(models.Manager):
    def create_obj_by_list(self, list):
        """
        用价格列表更新记录
        :return:
        """
        if list is not None:
            stock = StockProfile.objects.get(exchange_no=list[0], stock_code=list[1])
            obj = self.create(
                stock=stock,
                topen=list[2],
                lclose=list[3],
                now=list[4],
                high=list[5],
                low=list[6],
                buy_vs=list[7],
                sale_vs=list[8],
                voturnover=list[9],
                vaturnover=list[10],
                buy1_num=list[11],
                buy1_price=list[12],
                buy2_num=list[13],
                buy2_price=list[14],
                buy3_num=list[15],
                buy3_price=list[16],
                buy4_num=list[17],
                buy4_price=list[18],
                buy5_num=list[19],
                buy5_price=list[20],
                sale1_num=list[21],
                sale1_price=list[22],
                sale2_num=list[23],
                sale2_price=list[24],
                sale3_num=list[25],
                sale3_price=list[26],
                sale4_num=list[27],
                sale4_price=list[28],
                sale5_num=list[29],
                sale5_price=list[30],
                date=list[31],
                time=list[32],
                chg_value=list[33],
                chg_percent=list[34],
            )
            if obj:
                return True
            else:
                return False

# Create your models here.
class StockProfile(models.Model):
    """
    股票概要信息
    """
    class Meta:
        verbose_name = _('股票概要信息')
        verbose_name_plural = _('股票概要信息')

    company_code = models.CharField(unique=True, max_length=7, verbose_name=_('公司代码'))
    company_abb = models.CharField(null=True, max_length=100, verbose_name=_('公司简称'))
    exchange_no = models.CharField(null=True, max_length=100, verbose_name=_('交易所代码'),
                                   help_text=_('上交所：SS，深交所：SZ'))
    stock_style = models.CharField(null=True, max_length=100, verbose_name=_('股票类型'),
                                   help_text=_('A/B/H等'))
    stock_code = models.CharField(unique=True, max_length=7, verbose_name=_('股票代码'))
    stock_abb = models.CharField(null=True, max_length=100, verbose_name=_('股票简称'))
    listing_date = models.DateField(null=True, verbose_name=_('挂牌日期'))
    general_capital = models.FloatField(null=True, verbose_name=_('总股本/股'))
    circulating_capital = models.FloatField(null=True, verbose_name=_('流通股本/股'))
    by_sector = models.CharField(null=True, blank=True, max_length=100, verbose_name=_('所属行业'))

    objects = models.Manager()
    extra_objects = ExtraStockProfileManager()

    def __str__(self):
        return self.company_abb

    def get_value_in_list(self):
        return [self.company_code, self.company_abb, self.exchange_no]


class StockPriceHis(models.Model):
    """
    股票历史价格
    """
    class Meta:
        verbose_name = _('股票历史价格')
        verbose_name_plural = _('股票历史价格')

    stock = models.ForeignKey(StockProfile, on_delete=models.CASCADE, verbose_name=_('股票'))
    date = models.DateField(null=True, verbose_name=_('日期'))
    tclose = models.FloatField(null=True, verbose_name=_('收盘价/元'))
    high = models.FloatField(null=True, verbose_name=_('最高价/元'))
    low = models.FloatField(null=True, verbose_name=_('最低价/元'))
    topen = models.FloatField(null=True, verbose_name=_('开盘价/元'))
    lclose = models.FloatField(null=True, verbose_name=_('前收盘/元'))
    chg = models.FloatField(null=True, verbose_name=_('涨跌额/元'))
    pchg = models.FloatField(null=True, verbose_name=_('涨跌幅/%'))
    voturnover = models.FloatField(null=True, verbose_name=_('成交量/手'))
    vaturnover = models.FloatField(null=True, verbose_name=_('成交额/元'))

    def __str__(self):
        return self.stock.stock_abb + ' : ' + self.date.strftime('%Y-%m-%d')


class StockBigExchange(models.Model):
    """
    股票大单交易信息
    """
    class Meta:
        verbose_name = _('股票大单交易信息')
        verbose_name_plural = _('股票大单交易信息')

    stock = models.ForeignKey(StockProfile, on_delete=models.CASCADE, verbose_name=_('股票'))
    date = models.DateField(null=True, verbose_name=_('日期'))
    zhulj = models.FloatField(null=True, verbose_name=_('主力净流入额/元'),
                              help_text=_('超大单加大单卖出成交额之和, 净额：流入-流出'))
    per_zhuli = models.FloatField(null=True, verbose_name=_('主力净流入占比/%'),
                                  help_text=_('净比：(流入-流出)/总成交额'))
    chaodd = models.FloatField(null=True, verbose_name=_('超大单净流入额/元'),
                               help_text=_('大于等于50万股或者100万元的成交单, 净额：流入-流出'))
    per_chaodd = models.FloatField(null=True, verbose_name=_('超大单净流入占比/%'),
                                   help_text=_('净比：(流入-流出)/总成交额'))
    dd = models.FloatField(null=True, verbose_name=_('大单净流入额/元'),
                           help_text=_('大于等于10万股或者20万元且小于50万股和100万元的成交单, 净额：流入-流出'))
    per_dd = models.FloatField(null=True, verbose_name=_('大单流入占比/%'),
                               help_text=_('净比：(流入-流出)/总成交额'))
    zd = models.FloatField(null=True, verbose_name=_('中单净流入额/元'),
                           help_text=_('大于等于2万股或者4万元且小于10万股和20万元的成交单, 净额：流入-流出'))
    per_zd = models.FloatField(null=True, verbose_name=_('中单净流入占比/%'),
                               help_text=_('净比：(流入-流出)/总成交额'))
    xd = models.FloatField(null=True, verbose_name=_('小单净流入额/元'),
                           help_text=_('小于2万股和4万元的成交单, 净额：流入-流出'))
    per_xd = models.FloatField(null=True, verbose_name=_('小单净流入占比/%'),
                               help_text=_('净比：(流入-流出)/总成交额'))

    def __str__(self):
        return self.stock.stock_abb + ' : ' + self.date.strftime('%Y-%m-%d')


class StockPriceOnLine(models.Model):
    """
    股票实时价格
    """
    class Meta:
        verbose_name = _('股票实时价格')
        verbose_name_plural = _('股票实时价格')

    stock = models.ForeignKey(StockProfile, on_delete=models.CASCADE, verbose_name=_('股票'))
    topen = models.FloatField(null=True, verbose_name=_('开盘价/元'))
    lclose = models.FloatField(null=True, verbose_name=_('前收盘/元'))
    now = models.FloatField(null=True, verbose_name=_('当前价/元'))
    high = models.FloatField(null=True, verbose_name=_('最高价/元'))
    low = models.FloatField(null=True, verbose_name=_('最低价/元'))
    buy_vs = models.FloatField(null=True, verbose_name=_('竞买价/元'))
    sale_vs = models.FloatField(null=True, verbose_name=_('竞卖价/元'))
    voturnover = models.FloatField(null=True, verbose_name=_('成交量/手'))
    vaturnover = models.FloatField(null=True, verbose_name=_('成交金额/元'))
    buy1_num = models.FloatField(null=True, verbose_name=_('买一数/手'))
    buy1_price = models.FloatField(null=True, verbose_name=_('买一价/元'))
    buy2_num = models.FloatField(null=True, verbose_name=_('买二数/手'))
    buy2_price = models.FloatField(null=True, verbose_name=_('买二价/元'))
    buy3_num = models.FloatField(null=True, verbose_name=_('买三数/手'))
    buy3_price = models.FloatField(null=True, verbose_name=_('买三价/元'))
    buy4_num = models.FloatField(null=True, verbose_name=_('买四数/手'))
    buy4_price = models.FloatField(null=True, verbose_name=_('买四价/元'))
    buy5_num = models.FloatField(null=True, verbose_name=_('买五数/手'))
    buy5_price = models.FloatField(null=True, verbose_name=_('买五价/元'))
    sale1_num = models.FloatField(null=True, verbose_name=_('卖一数/手'))
    sale1_price = models.FloatField(null=True, verbose_name=_('卖一价/元'))
    sale2_num = models.FloatField(null=True, verbose_name=_('卖二数/手'))
    sale2_price = models.FloatField(null=True, verbose_name=_('卖二价/元'))
    sale3_num = models.FloatField(null=True, verbose_name=_('卖三数/手'))
    sale3_price = models.FloatField(null=True, verbose_name=_('卖三价/元'))
    sale4_num = models.FloatField(null=True, verbose_name=_('卖四数/手'))
    sale4_price = models.FloatField(null=True, verbose_name=_('卖四价/元'))
    sale5_num = models.FloatField(null=True, verbose_name=_('卖五数/手'))
    sale5_price = models.FloatField(null=True, verbose_name=_('卖五价/元'))
    date = models.DateField(null=True, verbose_name=_('日期'))
    time = models.TimeField(null=True, verbose_name=_('时间'))
    chg_value = models.FloatField(null=True, verbose_name=_('涨跌额/元'))
    chg_percent = models.FloatField(null=True, verbose_name=_('涨跌幅'))

    objects = models.Manager()
    extra_objects = ExtraStockPriceOnLineManager()

    def __str__(self):
        return self.stock.stock_abb + ' : ' + self.date.strftime('%Y-%m-%d') + ' ' + self.time.strftime('%H:%M:%S %f')

stockans/forms.py
from django import forms


class ProfileSearchForm(forms.Form):
    """
    概要信息搜索框
    """
    stock_abb = forms.CharField(label='股票简称', max_length=100)
    stock_code = forms.CharField(label='股票代码', max_length=100)
    start_date = forms.DateField(label='起始日期')
    end_date = forms.DateField(label='结束日期')


YEAR_IN_SCHOOL_CHOICES = (
    ('FR', 'Freshman'),
    ('SO', 'Sophomore'),
    ('JR', 'Junior'),
    ('SR', 'Senior'),
)


class ProfileActionForm(forms.Form):
    """
    概要信息操作框
    """
    action = forms.ChoiceField(choices=YEAR_IN_SCHOOL_CHOICES,)

stockans/views.py
from django.shortcuts import render
from . import models as stockans_models
from mainpage.models import Domain
from library.stockans_extra import ChangeList_StockAns
from library.stockdataspider import GetStockProfile
from django.http import HttpResponseRedirect, JsonResponse
from apscheduler.schedulers.background import BackgroundScheduler
from django_apscheduler.jobstores import DjangoJobStore, register_events, register_job
from .cron import get_stock_attentioned_price_online, pull_price_online

scheduler = BackgroundScheduler()
scheduler.add_jobstore(DjangoJobStore(), 'default')


@register_job(scheduler, 'interval', seconds=20)
def get_price_online():
    get_stock_attentioned_price_online()

register_events(scheduler)
# scheduler.start()


# Create your views here.
def update_stockprofile(request):
    """
    更新概要信息分配
    :param request:
    :return:
    """
    ss_domain = Domain.extra_objects.get_stock_profile_spider_url("上交所")
    sz_domain = Domain.extra_objects.get_stock_profile_spider_url("深交所")
    if request.method == "POST":
        action_type = request.POST['action']
        if action_type is not None and action_type != "":
            g = GetStockProfile(ss_domain=ss_domain, sz_domain=sz_domain)
            if action_type == "update_all":
                data_list = g.get_all_stock_profile()
            if action_type == "update_ss":
                data_list = g.get_ss_stock_profile()
            if action_type == "update_sz":
                data_list = g.get_sz_stock_profile()
            update_num = stockans_models.StockProfile.extra_objects.update_by_bulk(data_list)
        else:
            update_num = 0

    return JsonResponse({'update_num': update_num})


def profile_list(request):
    """
    概要信息列表
    :param request:
    :return:
    """

    model = stockans_models.StockProfile
    cl = ChangeList_StockAns(request, model)

    return render(request, 'stockans/profile_list.html', {'cl': cl})


def price_online(request):
    """
    实时价格信息
    :param request:
    :return:
    """
    stock_queryset = stockans_models.AttentionedStock.extra_objects.get_attentioned_stock_by_user(request)
    return render(request, 'stockans/price_online.html', {'stock_queryset': stock_queryset})


def update_price_online_data(request):
    """
    实时更新价格信息
    :param request:
    :return:
    """
    stock_queryset = stockans_models.AttentionedStock.extra_objects.get_attentioned_stock_by_user(request)
    price_data = pull_price_online(stock_queryset)
    return JsonResponse(price_data, safe=False)

stockans/templates/stockans/demo.html
{% load i18n static %}
{% if result_hidden_fields %}
<div class="hiddenfields">{# DIV for HTML validation #}
{% for item in result_hidden_fields %}{{ item }}{% endfor %}
</div>
{% endif %}
{% if results %}
<div class="results">
<table id="result_list">
<thead>
<tr>
{% for header in result_headers %}
<th scope="col" {{ header.class_attrib }}>
   {% if header.sortable %}
     {% if header.sort_priority > 0 %}
       <div class="sortoptions">
         <a class="sortremove" href="{{ header.url_remove }}" title="{% trans "Remove from sorting" %}"></a>
         {% if num_sorted_fields > 1 %}<span class="sortpriority" title="{% blocktrans with priority_number=header.sort_priority %}Sorting priority: {{ priority_number }}{% endblocktrans %}">{{ header.sort_priority }}</span>{% endif %}
         <a href="{{ header.url_toggle }}" class="toggle {% if header.ascending %}ascending{% else %}descending{% endif %}" title="{% trans "Toggle sorting" %}"></a>
       </div>
     {% endif %}
   {% endif %}
   <div class="text">{% if header.sortable %}<a href="{{ header.url_primary }}">{{ header.text|capfirst }}</a>{% else %}<span>{{ header.text|capfirst }}</span>{% endif %}</div>
   <div class="clear"></div>
</th>{% endfor %}
</tr>
</thead>
<tbody>
{% for result in results %}
{% if result.form.non_field_errors %}
    <tr><td colspan="{{ result|length }}">{{ result.form.non_field_errors }}</td></tr>
{% endif %}
<tr class="{% cycle 'row1' 'row2' %}">{% for item in result %}{{ item }}{% endfor %}</tr>
{% endfor %}
</tbody>
</table>
</div>
{% endif %}

stockans/templates/stockans/price_online.html
{% extends 'utils/app_base.html' %}
{% load static %}
{% load stockans_filters_tags %}
{% block css %}
    <link rel="stylesheet" href="{% static 'stockans/css/profile_list.css' %}">
{% endblock %}
{% block content %}
<div class="price_online_container" style="width: 100%; padding: 10px;">
<div class="table_row" style="width: 100%; margin: 0; padding: 0;">
    <table class="table table-striped table-hover table-sm table-bordered">
    <thead class="thead-light">
    <tr>
        <th scope="col">股票代码</th>
        <th scope="col">股票简称</th>
        <th scope="col">日期</th>
        <th scope="col">时间</th>
        <th scope="col">开盘价/元</th>
        <th scope="col">昨收盘/元</th>
        <th scope="col">现价/元</th>
        <th scope="col">涨跌额/元</th>
        <th scope="col">涨跌幅</th>
        <th scope="col">最高价/元</th>
        <th scope="col">最低价/元</th>
    </tr>
    </thead>
    {% if stock_queryset %}
        <tbody>
        {% for stock in stock_queryset %}
            <tr id="{{ stock.stock__stock_code }}">
                <td>{{ stock.stock__stock_code }}</td>
                <td>{{ stock.stock__stock_abb }}</td>
                <td class="stock_data_online"></td>
                <td class="stock_data_online"></td>
                <td class="stock_data_online"></td>
                <td class="stock_data_online"></td>
                <td class="stock_data_online"></td>
                <td class="stock_data_online"></td>
                <td class="stock_data_online"></td>
                <td class="stock_data_online"></td>
                <td class="stock_data_online"></td>
            </tr>
        {% endfor %}
      </tbody>
    {% endif %}
    </table>
</div>
<div class="chart_row" style="width: 100%; margin: 0; padding: 0;">
    <div id="graph_data_online" style="width: 100%; height: 500px;"></div>
</div>
</div>
{% endblock %}
{% block js %}
    <script src="{% static 'stockans/js/echarts.js' %}"></script>
    <script type="text/javascript">
    $(document).ready(
        update_price_online_cell()
        {#timer = self.setInterval("update_price_online_cell()", 5000)#}
    );
    
    function get_chart_data(origin_data) {
        chart_data = [];
        for(i = 0; i <= origin_data.length-1; i++){
            data_per_time = [];
            var date = origin_data[i][0] + ' ' + origin_data[i][1];
            date = date.replace(/-/g,'/');
            data_per_time[0] = new Date(date).getTime();
            data_per_time[1] = origin_data[i][5];
            chart_data.push(data_per_time);
        }
        return chart_data;
    }

    function update_price_online_cell() {
        $.get("{% url 'stockans:update_price_online_data' %}", function(price_online_data){

            /*---------------------charts代码---------------------*/
            var legend_data = [];
            var series_data = [];
            /*---------------------charts代码---------------------*/

            for(var stock_num=0; stock_num <= price_online_data.length-1; stock_num++){
                var table_row =document.getElementById(price_online_data[stock_num]["code"]);
                var table_cell_exist = table_row.getElementsByClassName("stock_data_online");
                var price_per_stock = JSON.parse(price_online_data[stock_num]["price"]);

                /*---------------------charts代码---------------------*/
                var series_unit = new Object();
                legend_data.push(price_online_data[stock_num]["abb"]);
                series_unit.name = price_online_data[stock_num]["abb"];
                series_unit.type = 'line';
                series_unit.symbol = 'none';
                series_unit.data = get_chart_data(price_per_stock);
                series_data.push(series_unit);
                /*---------------------charts代码---------------------*/

                if(price_per_stock.length>1) {
                    var price_per_stock_per_time = price_per_stock.pop();
                    var price_per_stock_previous_time = price_per_stock.pop();
                    for (var item_num = 0; item_num <= price_per_stock_per_time.length - 1; item_num++) {
                        table_cell_exist[item_num].innerHTML = price_per_stock_per_time[item_num];
                        if(price_per_stock_per_time[item_num] > price_per_stock_previous_time[item_num]) {
                            table_cell_exist[item_num].style.color = "red";
                        }
                        if(price_per_stock_per_time[item_num] < price_per_stock_previous_time[item_num]) {
                            table_cell_exist[item_num].style.color = "green";
                        }
                    }
                }
            }

            myChart.setOption({
                legend:{
                    data:legend_data
                },
                series:series_data
            });
        });
    }


    var myChart = echarts.init(document.getElementById('graph_data_online'));

    // 指定图表的配置项和数据
    var option = {
        tooltip: {
            trigger: 'axis',
            axisPointer: {
                type: 'cross'
            }
            },
        grid: [
            {left: '3%', right: '3%', top: '8%', bottom: '10%'},
        ],
        xAxis: [
            {
                type: 'time',
            }
            ],
        yAxis: [
            {
                type: 'value'
            }
            ],
        series: []
    };

    // 使用刚指定的配置项和数据显示图表。
    myChart.setOption(option);
    </script>
{% endblock %}

stockans/templates/stockans/profile_list.html
{% extends 'utils/app_base.html' %}
{% load static %}
{% load stockans_filters_tags %}
{% block css %}
    <link rel="stylesheet" href="{% static 'stockans/css/profile_list.css' %}">
{% endblock %}
{% block content %}
{% result_list_tag cl %}
{% endblock %}
{% block js %}
    <script type="text/javascript">
        var options = {
        url: "{% url 'stockans:update_stockprofile' %}",
        type: "post",
        success: successfun,
        dataType: "json",
        {#timeout: 3000#}
    };
        $('#actions_btn').click(function () {
            $('#actions_list').ajaxForm(options);
        });
        function successfun(data, status) {
            alert(data.update_num + "条数据更新成功！")
        }
    </script>
{% endblock %}

stockans/templates/stockans/result_list.html
<div class="stockprofile_content">
<form id="changelist-search" method="get">
    <div class="form-group form-row">
        <div class="col">
        <label for="searchbar" class="float-right"><span><i class="glyphicon glyphicon-search"></i></span></label>
        </div>
        <div class="col">
        <input class="form-control form-control-sm" id="searchbar" type="text" name="q"  placeholder="股票代码">
        </div>
        <div class="col">
        <input type="submit" class="sts_btn" value="搜索">
        </div>
    </div>
</form>
<form id="actions_list" method="post">
{% csrf_token %}
<div class="form-group">
    <label for="action" class="float-left">操作:</label>
    <select id="action" name="action" class="form-control float-left actions_select" required>
        <option value="" selected>------------</option>
        <option value="update_all">更新所有</option>
        <option value="update_ss">更新上交所</option>
        <option value="update_sz">更新深交所</option>
    </select>
    &nbsp;
    <input type="submit" id="actions_btn" class="sts_btn" value="执行">
</div>
</form>
<div class="results">
    <table class="table table-striped table-hover table-sm table-bordered">
    <thead class="thead-light">
    <tr>
    {% for header in headers %}
    <th scope="col">
       <a href="{{ header.url_primary }}">{{ header.text|capfirst }}</a>
    </th>
    {% endfor %}
    </tr>
    </thead>
    {% if results %}
        <tbody>
        {% for result in results %}
            <tr>
              {% for item in result %}
                  {% if forloop.counter == 1 %}
                  <th scope="row">{{ item }}</th>
                  {% else %}
                  <td>{{ item }}</td>
                  {% endif %}
              {% endfor %}
            </tr>
        {% endfor %}
      </tbody>
    {% endif %}
    </table>
</div>
<div class="paginator row">
    <div class="paginator-stable col" style="text-align: right;">
    <!-- 如果当前页还有上一页，显示一个上一页的按钮 -->
    {% if results.has_previous %} <a href="{{ previous_page_link }}">上一页</a> {% endif %}
    <!-- 显示当前页面信息 -->
    <span class="current">第 {{ results.number }} 页 / 共 {{ results.paginator.num_pages }} 页</span>
    <!-- 如果当前页还有下一页，显示一个下一页的按钮 -->
    {% if results.has_next %} <a href="{{ next_page_link }}">下一页</a> {% endif %}
    </div>
    <div class="paginator-search col">
    <form id="paginator-form" method="get">
        <input type="text" name="sp" id="paginator_search_num">
        <input type="submit" id="paginator_search_btn" value="跳转">
    </form>
    </div>
</div>
</div>